name: TAD_Character_Engineer_2
version: '${project.version}'
main: jp.houlab.mochidsuki.tad_character_engineer_2.Main
api-version: '1.20'

depend: [ TowerAandD ]

commands:
  tce:
    aliases: [ tadce ]
    description: Command description
    permission: TAD_Character_Engineer.command.tce
    permission-message: Permission denied
    usage: Command usage